#!/usr/bin/env bash
#Comment

i=1
h=0
while (i <20)
	case

	4) 
	echo "Hour: $hour"
	echo minute 
	((minute ++))

	9) 
	echo "$minute"
	((hour ++))
	((minute = 1))

	echo "$minute"
	((minute ++))
done	
