#!/usr/bin/env bash
#Comment

minute=1
h=0
while [ $h -le 12 ] && [ $minute -le 59 ]; do 
	case $minute in 

		1) 
			echo "Hour: $h"
			echo $minute 
			((minute++));;

		59) 
			echo "$minute"
			((h++))
			((minute = 1));;

		*) 
			echo "$minute"
			((minute++));;

	esac
done	
